name: LiveContainer + SideStore - Build

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build LiveContainer + SideStore
    runs-on: macos-latest
    env:
      scheme: LiveContainer
      archive_path: archive

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Scheme
        id: scheme
        run: |
          if [ $scheme = default ]
          then
            scheme_list=$(xcodebuild -list -json | tr -d "\n")
            scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
            echo "Using default scheme: $scheme"
          else
            echo "Using configured scheme: $scheme"
          fi
          echo "scheme=$scheme" >> $GITHUB_OUTPUT

      - name: Set filetype_parameter
        id: filetype_parameter
        run: |
          filetype_parameter=`ls -A | grep -i \\.xcworkspace\$ && echo workspace || echo project`
          echo "filetype_parameter=$filetype_parameter" >> $GITHUB_OUTPUT

      - name: Set file_to_build
        id: file_to_build
        run: |
          file_to_build=`ls -A | grep -i \\.xcworkspace\$ || ls -A | grep -i \\.xcodeproj\$`
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          echo "file_to_build=$file_to_build" >> $GITHUB_OUTPUT

      - name: Archive Project
        env:
          scheme: ${{ steps.scheme.outputs.scheme }}
          filetype_parameter: ${{ steps.filetype_parameter.outputs.filetype_parameter }}
          file_to_build: ${{ steps.file_to_build.outputs.file_to_build }}
        run: |
          xcodebuild archive -archivePath "$archive_path" -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -sdk iphoneos -arch arm64 -configuration Release | xcpretty && exit ${PIPESTATUS[0]}

      - name: Build LiveContainer + SideStore IPA
        run: |
          sh .github/night.sh

      - name: Upload LiveContainer+SideStore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LiveContainer+SideStore.ipa
          path: ${{ env.scheme }}+SideStore.ipa
